package configuration

var HtmlAtrTable = map[string][]string{
	"!DOCTYPE": {"html"},
	"":         nil,
	"!--":      nil,
	"a":        {"download", "href", "hreflang", "ping", "referrerpolicy", "rel", "target", "type"},
	"abbr":     {},
	"address":  {},
	"area":     {"alt", "coords", "download", "href", "ping", "referrerpolicy", "rel", "shape", "target"},
	"article":  {},
	"aside":    {},
	"audio": {"autoplay", "controls", "controlslist", "crossorigin", "disableremoteplayback", "loop", "muted",
		"preload", "src"},
	"b":          {},
	"base":       {"href", "target"},
	"bdi":        {},
	"bdo":        {},
	"blockquote": {"cite"},
	"body": {"alink", "background", "bgcolor", "bottommargin", "leftmargin", "link", "rightmargin", "text",
		"topmargin", "vlink"},
	"br": {},
	"button": {"autofocus", "autocomplete", "disabled", "form", "formaction", "formenctype", "formmethod",
		"formnovalidate", "formtarget", "name", "popovertarget", "popovertargetaction", "type", "value"},
	"canvas":     {"height", "width"},
	"caption":    {},
	"cite":       {},
	"code":       {},
	"col":        {"span"},
	"colgroup":   {"span"},
	"data":       {"value"},
	"datalist":   {},
	"dd":         {},
	"del":        {"cite", "datetime"},
	"details":    {"open"},
	"dfn":        {},
	"dialog":     {"open"},
	"div":        {},
	"dl":         {},
	"dt":         {},
	"em":         {},
	"embed":      {"height", "src", "type", "width"},
	"fieldset":   {"disabled", "form", "name"},
	"figcaption": {},
	"figure":     {},
	"footer":     {},
	"form": {"accept", "accept-charset", "autocapitalize", "autocomplete", "name", "rel", "action", "enctype",
		"method", "novalidate", "target"},
	"h1":     {},
	"h2":     {},
	"h3":     {},
	"h4":     {},
	"h5":     {},
	"h6":     {},
	"head":   {},
	"header": {},
	"hgroup": {},
	"hr":     {},
	"html":   {"xmlns"},
	"i":      {},
	"iframe": {"allow", "allowfullscreen", "allowpaymentrequest", "credentialless", "csp", "height", "loading",
		"name", "refferrerpolicy", "sandbox", "src", "srcdoc", "width"},
	"img": {"alt", "crossorigin", "decoding", "elementtiming", "fetchpriority", "height", "ismap", "loading",
		"referrerpolicy", "sizes", "src", "srcset", "width", "usemap"},
	"input": {"accept", "alt", "autocapitalize", "autocomplete", "autofocus", "capture", "checked", "dirname",
		"disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "height",
		"inputmode", "list", "max", "maxlength", "min", "minlength", "multiple", "name", "pattern", "placeholder",
		"popovertarget", "popovertargetaction", "readonly", "required", "size", "src", "step", "tabindex", "title",
		"type", "value", "width", "autocorrect", "incremental", "orient", "results", "webkitdirectory"},
	"ins":    {"cite", "datetime"},
	"kbd":    {},
	"label":  {"for"},
	"legend": {},
	"li":     {"value"},
	"link": {"as", "blocking", "crossorigin", "disabled", "fetchpriority", "href", "hreflang", "imagesizes",
		"imagesrcset", "integrity", "media", "referrerpolicy", "rel", "sizes", "title", "type"},
	"main":     {},
	"map":      {"name"},
	"mark":     {},
	"menu":     {},
	"meta":     {"charset", "content", "http-equiv", "name"},
	"meter":    {"value", "min", "max", "low", "high", "optimum", "form"},
	"nav":      {},
	"noscript": {},
	"object":   {"data", "form", "height", "name", "type", "usemap", "width"},
	"ol":       {"reversed", "start", "type"},
	"optgroup": {"disabled", "label"},
	"option":   {"disabled", "label", "selected", "value"},
	"output":   {"for", "form", "name"},
	"p":        {},
	"picture":  {},
	"portal":   {"referrerpolicy", "src"},
	"pre":      {},
	"progress": {"max", "value"},
	"q":        {"cite"},
	"rp":       {},
	"rt":       {},
	"ruby":     {},
	"s":        {},
	"samp":     {},
	"script": {"async", "blocking", "crossorigin", "defer", "fetchpriority", "integrity", "nomodule", "nonce",
		"referrerpolicy", "src", "type"},
	"search":   {},
	"section":  {},
	"select":   {"autocomplete", "autofocus", "disabled", "form", "multiple", "name", "required", "size"},
	"slot":     {"name"},
	"small":    {},
	"source":   {"type", "src", "srcset", "sizes", "media", "height", "width"},
	"span":     {},
	"strong":   {},
	"style":    {"blocking", "media", "nonce"},
	"sub":      {},
	"summary":  {},
	"sup":      {},
	"svg":      {},
	"table":    {},
	"tbody":    {},
	"td":       {"colspan", "headers", "rowspan"},
	"template": {},
	"textarea": {"autocapitalize", "autocomplete", "autocorrect", "autofocus", "cols", "dirname", "disabled",
		"form", "maxlength", "minlength", "name", "placeholder", "readonly", "required", "rows", "spellcheck", "wrap"},
	"tfoot": {},
	"th":    {"abbr", "colspan", "headers", "rowspan", "scope"},
	"thead": {},
	"time":  {"datetime"},
	"title": {},
	"tr":    {},
	"track": {"default", "kind", "label", "src", "srclang"},
	"u":     {},
	"ul":    {},
	"var":   {},
	"video": {"autoplay", "controls", "controlslist", "crossorigin", "disablepictureinpicture",
		"disableremoteplayback", "height", "loop", "muted", "playsinline", "poster", "preload", "src", "width"},
	"wbr": {},
}

var SelfClosingHtmlTag = []string{"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"}

var GlobalAtrTable = map[string]string{
	"accessKey":             "",
	"aria":                  "",
	"autocapitalize":        "",
	"autofocus":             "",
	"class":                 "",
	"contenteditable":       "",
	"data":                  "",
	"dir":                   "",
	"draggable":             "",
	"enterKeyHint":          "",
	"exportParts":           "",
	"hidden":                "",
	"id":                    "",
	"inert":                 "",
	"inputMode":             "",
	"is":                    "",
	"itemId":                "",
	"itemProp":              "",
	"itemRef":               "",
	"itemScope":             "",
	"itemType":              "",
	"lang":                  "",
	"nonce":                 "",
	"part":                  "",
	"popover":               "",
	"role":                  "",
	"slot":                  "",
	"spellcheck":            "",
	"style":                 "",
	"tabindex":              "",
	"title":                 "",
	"translate":             "",
	"virtualKeyBoardPolicy": "",
}

var GlobalEventAtrTable = map[string]string{
	"onabort":             "",
	"onautocomplete":      "",
	"onautocompleteerror": "",
	"onblur":              "",
	"oncancel":            "",
	"oncanplay":           "",
	"oncanplaythrough":    "",
	"onchange":            "",
	"onclick":             "",
	"onclose":             "",
	"oncontextmenu":       "",
	"oncuechange":         "",
	"ondblclick":          "",
	"ondrag":              "",
	"ondragend":           "",
	"ondragenter":         "",
	"ondragleave":         "",
	"ondragover":          "",
	"ondragstart":         "",
	"ondrop":              "",
	"ondurationchange":    "",
	"onemptied":           "",
	"onended":             "",
	"onerror":             "",
	"onfocus":             "",
	"oninput":             "",
	"oninvalid":           "",
	"onkeydown":           "",
	"onkeypress":          "",
	"onkeyup":             "",
	"onload":              "",
	"onloadeddata":        "",
	"onloadedmetadata":    "",
	"onloadstart":         "",
	"onmousedown":         "",
	"onmouseenter":        "",
	"onmouseleave":        "",
	"onmousemove":         "",
	"onmouseout":          "",
	"onmouseover":         "",
	"onmouseup":           "",
	"onmousewheel":        "",
	"onpause":             "",
	"onplay":              "",
	"onplaying":           "",
	"onprogress":          "",
	"onratechange":        "",
	"onreset":             "",
	"onresize":            "",
	"onscroll":            "",
	"onseeked":            "",
	"onseeking":           "",
	"onselect":            "",
	"onshow":              "",
	"onsort":              "",
	"onstalled":           "",
	"onsubmit":            "",
	"onsuspend":           "",
	"ontimeupdate":        "",
	"ontoggle":            "",
	"onvolumechange":      "",
	"onwaiting":           "",
}

var SpecificAtrTable = map[string]string{
	"abbr":                    "Specifies a shorter version of the content in a cell.",
	"accept":                  "Defines the file types the file input should accept",
	"accept-charset":          "Specifies the character encodings that are to be used for the form submission",
	"action":                  "Specifies where to send the form-data when a form is submitted.",
	"alink":                   "Sets the color of an active link (deprecated in HTML5).",
	"allow":                   "",
	"allowfullscreen":         "Allows a frame to be displayed in full-screen mode.",
	"allowpaymentrequest":     "",
	"alt":                     " Provides alternative text for an image.",
	"as":                      "",
	"async":                   "Indicates that the script should be executed asynchronously.",
	"autocapitalize":          "Controls whether and how text input is automatically capitalized.",
	"autocomplete":            "Specifies whether a form or an input field should have autocomplete enabled.",
	"autocorrect":             "",
	"autofocus":               "Specifies that a form element should automatically get focus when the page loads.",
	"autoplay":                "Specifies that the audio or video should start playing as soon as it is ready.",
	"background":              "",
	"bgcolor":                 "",
	"blocking":                "",
	"bottommargin":            "",
	"capture":                 "",
	"charset":                 "Specifies the character encoding for the HTML document.",
	"checked":                 "Indicates whether an input element is selected by default.",
	"cite":                    "Specifies a reference to the source of a quote or information.",
	"cols":                    "Specify the size of a textarea.",
	"colspan":                 "Specify how many columns a cell should span in a table.",
	"content":                 "",
	"controls":                "Specifies that audio/video controls should be displayed.",
	"controlslist":            "",
	"coords":                  "",
	"credentialless":          "",
	"crossorigin":             "How to handle cross-origin requests for the element.",
	"csp":                     "",
	"data":                    "",
	"datetime":                "Specifies the date and time.",
	"decoding":                "",
	"default":                 "",
	"defer":                   "",
	"dirname":                 "",
	"disabled":                "Indicates that the user cannot interact with the element.",
	"disablepictureinpicture": "",
	"disableremoteplayback":   "",
	"download":                "Specifies that the target will be downloaded when a user clicks on the hyperlink.",
	"elementtiming":           "",
	"enctype":                 "",
	"fetchpriority":           "",
	"for":                     "",
	"form":                    "",
	"formaction":              "",
	"formenctype":             "",
	"formmethod":              "",
	"formnovalidate":          "",
	"formtarget":              "",
	"headers":                 "",
	"height":                  "",
	"high":                    "",
	"href":                    "Specifies the URL of the page the link goes to.",
	"hreflang":                "",
	"html":                    "",
	"http-equiv":              "",
	"imagesizes":              "",
	"imagesrcset":             "",
	"incremental":             "",
	"inputmode":               "",
	"integrity":               "",
	"ismap":                   "",
	"kind":                    "",
	"label":                   "",
	"leftmargin":              "",
	"link":                    "",
	"list":                    "",
	"loading":                 "",
	"loop":                    "",
	"low":                     "",
	"max":                     "",
	"maxlength":               "Specify the maximum lengths of text in an input field.",
	"media":                   "",
	"method":                  "",
	"min":                     "",
	"minlength":               "Specify the minimum lengths of text in an input field.",
	"multiple":                "Indicates that multiple values can be entered or selected.",
	"muted":                   "",
	"name":                    "",
	"nomodule":                "",
	"nonce":                   "",
	"novalidate":              "",
	"open":                    "",
	"optimum":                 "",
	"orient":                  "",
	"pattern":                 "",
	"ping":                    "",
	"placeholder":             "Provides a hint to the user about what can be entered in the field.",
	"playsinline":             "",
	"popovertarget":           "",
	"popovertargetaction":     "",
	"poster":                  "",
	"preload":                 "",
	"readonly":                "Indicates that the input field is read-only.",
	"referrerpolicy":          "",
	"refferrerpolicy":         "",
	"rel":                     "",
	"required":                "Specifies that an input field must be filled out before submitting the form.",
	"results":                 "",
	"reversed":                "",
	"rightmargin":             "",
	"rows":                    "Specify the size of a textarea.",
	"rowspan":                 "Specify how many rows a cell should span in a table.",
	"sandbox":                 "",
	"scope":                   "",
	"selected":                "",
	"shape":                   "",
	"size":                    "",
	"sizes":                   "",
	"span":                    "",
	"spellcheck":              "",
	"src":                     "Specifies the URL of an image.",
	"srcdoc":                  "",
	"srclang":                 "",
	"srcset":                  "",
	"start":                   "",
	"step":                    "",
	"tabindex":                "",
	"target":                  "",
	"text":                    "",
	"topmargin":               "",
	"type":                    "Specifies the type of an <input> element.",
	"usemap":                  "",
	"value":                   "Specifies the value of an <input> element.",
	"vlink":                   "",
	"webkitdirectory":         "",
	"width":                   "",
	"wrap":                    "",
	"xmlns":                   "",
}

var BoolAtr = []string{"async", "autoplay", "checked", "controls", "default", "defer", "disabled", "html", "ismap", "loop",
	"multiple", "muted", "novalidate", "open", "readonly", "required", "reversed", "selected", "popover"}

var GlobAriaName = []string{"atomic", "busy", "controls", "current", "describedby", "description", "details", "disabled",
	"dropeffect", "errormessage", "flowto", "grabbed", "haspopup", "hidden", "invalid", "keyshortcuts", "label",
	"labelledby", "live", "owns", "relevant", "roledescription"}
