package configuration

var SvgAtrTable = map[string][]string{
	"a":                   {"download", "href", "hreflang", "ping", "referrerpolicy", "rel", "target", "type"},
	"animate":             {"accumulate", "additive", "attributeName", "attributeType", "begin", "by", "calcMode", "dur", "end", "fill", "from", "keySplines", "keyTimes", "max", "min", "repeatCount", "repeatDur", "restart", "to", "values"},
	"animateMotion":       {"accumulate", "additive", "begin", "by", "calcMode", "dur", "end", "fill", "from", "keyPoints", "keySplines", "keyTimes", "max", "min", "path", "repeatCount", "repeatDur", "restart", "rotate", "to", "values"},
	"animateTransform":    {"accumulate", "additive", "attributeName", "attributeType", "begin", "by", "calcMode", "dur", "end", "fill", "from", "keySplines", "keyTimes", "max", "min", "repeatCount", "repeatDur", "restart", "to", "type", "values"},
	"circle":              {"cx", "cy", "r", "pathLength"},
	"clipPath":            {"clipPathUnits"},
	"defs":                {},
	"desc":                {},
	"ellipse":             {"cx", "cy", "rx", "ry", "pathLength"},
	"feBlend":             {"in", "in2", "mode"},
	"feColorMatrix":       {"in", "type", "values"},
	"feComponentTransfer": {"in"},
	"feComposite":         {"in", "in2", "operator", "k1", "k2", "k3", "k4"},
	"feConvolveMatrix":    {"in", "order", "kernelMatrix", "divisor", "bias", "targetX", "targetY", "edgeMode", "kernelUnitLength", "preserveAlpha"},
	"feDiffuseLighting":   {"in", "surfaceScale", "diffuseConstant", "kernelUnitLength"},
	"feDisplacementMap":   {"in", "in2", "scale", "xChannelSelector", "yChannelSelector"},
	"feDistantLight":      {"azimuth", "elevation"},
	"feDropShadow":        {"dx", "dy", "stdDeviation"},
	"feFlood":             {"flood-color", "flood-opacity"},
	"feFuncA":             {"type", "tableValues", "slope", "intercept", "amplitude", "exponent", "offset"},
	"feFuncB":             {"type", "tableValues", "slope", "intercept", "amplitude", "exponent", "offset"},
	"feFuncG":             {"type", "tableValues", "slope", "intercept", "amplitude", "exponent", "offset"},
	"feFuncR":             {"type", "tableValues", "slope", "intercept", "amplitude", "exponent", "offset"},
	"feGaussianBlur":      {"in", "stdDeviation", "edgeMode"},
	"feImage":             {"href", "preserveAspectRatio"},
	"feMerge":             {},
	"feMergeNode":         {"in"},
	"feMorphology":        {"in", "operator", "radius"},
	"feOffset":            {"in", "dx", "dy"},
	"fePointLight":        {"x", "y", "z"},
	"feSpecularLighting":  {"in", "surfaceScale", "specularConstant", "specularExponent", "kernelUnitLength"},
	"feSpotLight":         {"x", "y", "z", "pointsAtX", "pointsAtY", "pointsAtZ", "specularExponent", "limitingConeAngle"},
	"feTile":              {"in"},
	"feTurbulence":        {"baseFrequency", "numOctaves", "seed", "stitchTiles", "type"},
	"filter":              {"x", "y", "width", "height", "filterUnits", "primitiveUnits", "xlink:href"},
	"foreignObject":       {"x", "y", "width", "height"},
	"g":                   {},
	"hatch":               {"x", "y", "pitch", "rotate", "hatchUnits", "hatchContentUnits", "transform"},
	"hatchpath":           {"d", "offset", "strokeWidth", "pathLength"},
	"image":               {"href", "x", "y", "width", "height", "preserveAspectRatio", "xlink:href"},
	"line":                {"x1", "y1", "x2", "pathLength"},
	"linearGradient":      {"x1", "x2", "y1", "y2", "gradientUnits", "gradientTransform", "spreadMethod"},
	"marker":              {"markerHeight", "markerUnits", "markerWidth", "orient", "preserveAspectRatio", "refX", "refY", "viewBox"},
	"mask":                {"height", "maskContentUnits", "maskUnits", "width", "x", "y"},
	"metadata":            {},
	"mpath":               {"href"},
	"path":                {"d", "pathLength"},
	"pattern":             {"height", "patternContentUnits", "patternTransform", "patternUnits", "preserveAspectRatio", "viewBox", "width", "x", "y"},
	"polygon":             {"points", "pathLength"},
	"polyline":            {"points", "pathLength"},
	"radialGradient":      {"cx", "cy", "r", "fx", "fy", "fr", "gradientUnits", "gradientTransform", "spreadMethod"},
	"rect":                {"x", "y", "width", "height", "rx", "ry", "pathLength"},
	"script":              {"href", "type", "xlink:href"},
	"set":                 {"to", "attributeName", "attributeType", "begin", "dur", "end", "fill", "repeatCount", "repeatDur", "restart"},
	"stop":                {"offset", "stop-color", "stop-opacity"},
	"style":               {"type", "media", "title"},
	"svg":                 {"x", "y", "width", "height", "viewBox", "preserveAspectRatio", "version", "baseProfile", "xmlns", "xmlns:xlink"},
	"switch":              {},
	"symbol":              {"viewBox", "preserveAspectRatio", "refX", "refY"},
	"text":                {"x", "y", "dx", "dy", "rotate", "textLength", "lengthAdjust"},
	"textPath":            {"href", "startOffset", "method", "spacing"},
	"title":               {},
	"tspan":               {"x", "y", "dx", "dy", "rotate", "textLength", "lengthAdjust"},
	"use":                 {"href", "x", "y", "width", "height", "xlink:href"},
	"view":                {"viewBox", "preserveAspectRatio"},
}

var SvgGlobalAtr = map[string]string{
	"class":     "",
	"style":     "",
	"id":        "",
	"tabindex":  "",
	"xml:base":  "",
	"xml:lang":  "",
	"xml:space": "",
	"aria-":     "",
	"role":      "",
	"data-":     "",
}
